/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptrinhhdt_java.Chuong03.dohoa;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import laptrinhhdt_java.Chuong03.dohoa.frames.MyCoffee;
import laptrinhhdt_java.Chuong03.dohoa.frames.XuatDuLieuFrame;

/**
 *
 * @author Admin
 */
public class MyMainForm extends javax.swing.JFrame {

    XuatDuLieuFrame frm;
    MyCoffee frmCf;

    /**
     * Creates new form MyMainForm
     */
    public MyMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        txtMang1chieu = new javax.swing.JMenuItem();
        tctCoffee = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình thao tác với mảng 1 chiều");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mảng");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        txtMang1chieu.setText("Mảng 1 chiều");
        txtMang1chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMang1chieuActionPerformed(evt);
            }
        });
        jMenu2.add(txtMang1chieu);

        tctCoffee.setText("Coffee");
        tctCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tctCoffeeActionPerformed(evt);
            }
        });
        jMenu2.add(tctCoffee);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtMang1chieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMang1chieuActionPerformed
        // TODO add your handling code here:
        if (frm == null || frm.isClosed()) {
            frm = new XuatDuLieuFrame();
            desktop.add(frm);
            frm.setLocation(this.getWidth() / 2 - frm.getWidth() / 2, this.getHeight() / 2 - frm.getHeight() / 2);
            frm.setVisible(true);
        }

    }//GEN-LAST:event_txtMang1chieuActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        if (frmCf == null || frmCf.isClosed()) {
            try {
                frmCf = new MyCoffee();
                desktop.add(frmCf);
                frmCf.setLocation(this.getWidth() / 2 - frm.getWidth() / 2, this.getHeight() / 2 - frm.getHeight() / 2);
                frmCf.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(MyMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void tctCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tctCoffeeActionPerformed
        // TODO add your handling code here:
         if (frmCf == null || frmCf.isClosed()) {
            try {
                frmCf = new MyCoffee();
                desktop.add(frmCf);
                frmCf.setLocation(this.getWidth() / 2 - frmCf.getWidth() / 2, this.getHeight() / 2 - frmCf.getHeight() / 2);
                frmCf.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(MyMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tctCoffeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem tctCoffee;
    private javax.swing.JMenuItem txtMang1chieu;
    // End of variables declaration//GEN-END:variables
}
